  // ROW CONFIGURATION
    export const ROW_CONFIG = [
        {
        id: "quantity",
        label: "Menge",
        name: "quantity",
        type: "number",
        step: null,
        readonly: false,
        fix: true,
        defaultValue: "1",
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text label-col",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "price",
        label: "Preis (Stk. €)",
        name: "price",
        type: "number",
        step: "0.01",
        readonly: false,
        fix: true,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },


        {
        id: "purchase-price-gross",
        label: "Einkaufspreis inkl. Ust (€)",
        name: "purchasePriceGross",
        group: "purchase-gross",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "vat-rate-purchase",
        label: "USt. (%)",
        name: "vatRatePurchase",
        group: "purchase-gross",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "purchase-price",
        label: "Einkaufspreis (€)",
        name: "purchasePrice",
        group: "supplier-discount-1",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic ",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "supplier-discount1",
        label: "Lieferantenrabatt 1 (%)",
        name: "supplierDiscount1",
        group: "supplier-discount-1",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text w-50",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "discounted-price-1",
        label: "Rabattierter Preis 1 (€)",
        name: "discountedPrice1",
        group: "supplier-discount-2",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },    
        {
        id: "supplier-discount2",
        label: "Lieferantenrabatt 2 (%)",
        name: "supplierDiscount2",
        group: "supplier-discount-2",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "discounted-price-2",
        label: "Rabattierter Preis 2 (€)",
        name: "discountedPrice2",
        group: "supplier-discount-3",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "supplier-discount3",
        label: "Lieferantenrabatt 3 (%)",
        name: "supplierDiscount3",
        group: "supplier-discount-3",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "discounted-price-3",
        label: "Rabattierter Preis (€)",
        name: "discountedPrice3",
        group: "invoice",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "invoice-charges",
        label: "Fakturenspesen (€)",
        name: "invoiceCharges",
        group: "invoice",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "target-price",
        label: "Zielpreis (€)",
        name: "targetPrice",
        group: "supplier-cash",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "supplier-cash-discount",
        label: "Lieferantenskonto (%)",
        name: "supplierCashDiscount",
        group: "supplier-cash",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "cash-price",
        label: "Kassapreis (€)",
        name: "cashPrice",
        group: "procurement",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "procurement-costs",
        label: "Eigene Bezugskosten (€)",
        name: "procurementCosts",
        group: "procurement",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "cost-price",
        label: "Einstandspreis (€)",
        name: "costPrice",
        group: "overhead",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "overhead-rate",
        label: "Regien (%)",
        name: "overheadRate",
        group: "overhead",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "total-cost",
        label: "Selbstkosten (€)",
        name: "totalCost",
        group: "profit",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "profit-rate",
        label: "Gewinn (%)",
        name: "profitRate",
        group: "profit",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "cash-selling-price",
        label: "Kassaverkaufspreis (€)",
        name: "cashSellingPrice",
        group: "customer-cash",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "customer-cash-discount-rate",
        label: "Kundenskonto (%)",
        name: "customerCashDiscountRate",
        group: "customer-cash",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "target-selling-price",
        label: "Zielverkaufspreis (€)",
        name: "targetSellingPrice",
        group: "customer-discount-3",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "customer-discount-3",
        label: "Kundenrabatt 3 (%)",
        name: "customerDiscount3",
        group: "customer-discount-3",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "discounted-selling-price-2",
        label: "Rabattierter Zielverkaufspreis 2 (€)",
        name: "discountedSellingPrice2",
        group: "customer-discount-2",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "customer-discount-2",
        label: "Kundenrabatt 2 (%)",
        name: "customerDiscount2",
        group: "customer-discount-2",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "discounted-selling-price-1",
        label: "Rabattierter Zielverkaufspreis 1 (€)",
        name: "discountedSellingPrice1",
        group: "customer-discount-1",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "customer-discount-1",
        label: "Kundenrabatt 1 (%)",
        name: "customerDiscount1",
        group: "customer-discount-1",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "rrp",
        label: "UVP (€)",
        name: "rrp",
        group: "vat-selling",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "vat-rate",
        label: "USt. (%)",
        name: "vatRate",
        group: "vat-selling",
        type: "number",
        step: "0.01",
        readonly: false,
        spreadable: true,
        trClass: "border-b border-border/50",
        labelClass: "px-4 py-2 font-medium text-text",
        inputClass:
            "w-full px-2 py-1.5 border border-border rounded-md text-center text-sm bg-white " +
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition",
        },
        {
        id: "rrp-gross",
        label: "UVP inkl. USt. (€)",
        name: "rrpGross",
        group: "rrp-gross",
        type: "text",
        step: null,
        readonly: true,
        trClass: "border-b border-border/50 bg-primary/[0.03]",
        labelClass: "px-4 py-2 text-text/50 italic",
        inputClass:
            "w-full px-2 py-1.5 border border-transparent rounded-md text-center text-sm bg-transparent text-text/70",
        },
        {
        id: "result",
        label: "Ergebnis (€)",
        name: "result",
        type: "text",
        step: null,
        readonly: true,
        fix: true,
        trClass: "bg-primary/[0.06]",
        labelClass: "px-4 py-2.5 font-semibold text-primary",
        inputClass:
            "w-full px-2 py-1.5 border border-primary/25 rounded-md text-center text-sm font-semibold text-primary bg-white",
        },
    ];